# docker-compose.yaml

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    # command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    image: netsyntaxdev/crypnote:latest
    depends_on:
      - redis
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 4 MiB
      THEME_PAGE_TITLE: "IDECNET Crypnote"
      THEME_IMAGE: "https://cdn.discordapp.com/attachments/845856885151236096/1146531570455416973/crypnotelogo.png"
      THEME_TEXT: "Enví­a fácilmente notas o archivos totalmente encriptados y seguros."
      THEME_FAVICON: "https://cdn.discordapp.com/attachments/845856885151236096/1146474393577467964/shield.png"

    ports:
      - 80:8000

    # Optional health checks
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/live/"]
    #   interval: 1m
    #   timeout: 3s
    #   retries: 2
    #   start_period: 5s

